version: 2
jobs:
  test:
    docker:
      - image: cimg/node:12
    steps:
      - checkout
      - run: yarn install
      - run: make lint
      - run: make test

workflows:
  version: 2
  build:
    jobs:
      - test
