version: 2
jobs:
  test:
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - npm install
      - make lint
      - make test

workflows:
  version: 2
  build:
    jobs:
      - test
